eureka:
  instance:
    hostname: service-center-3
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka-server
#server:
#  port:
# 在server实例运行时使用-Dserver.port=8080