eureka:
  instance:
    hostname: service-center-1
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
spring:
  application:
    name: eureka-server
#server:
#  port:
# 在server实例运行时使用-Dserver.port=8080